id: I63E000FA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T16:15:49+00:00'
last_modified: '2022-06-08T16:22:38.183683+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24247
  title: སྤྱོད་འཇུག་འགྲེལ་པ་འཇམ་དབྱངས་བླ་མའི་ཞལ་ལུང་བདུད་རྩིའི་ཐིག་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    49E8:
      image_group_id: I1KG24322
      title: ''
      total_pages: 636
      order: 1
      base_file: 49E8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
