id: I63E000FA
legacy_id: P010631
ocr_import_info:
  bdrc_scan_id: W1KG24247
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T16:11:49'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T13:41:39.224683+00:00'
last_modified: 2022-08-31 21:42:06.486458
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG24247
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG24247
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྤྱོད་འཇུག་འགྲེལ་པ་འཇམ་དབྱངས་བླ་མའི་ཞལ་ལུང་བདུད་རྩིའི་ཐིག་པ།
  author: མཁན་པོ་ཀུན་དཔལ།
statistics:
  ocr_word_mean_confidence_index: 0.8531481165979685
  ocr_word_median_confidence_index: 0.9200000166893005
quality: null
bases:
  I1KG24322:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG24322
      total_pages: 636
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG24322.txt
    statistics:
      ocr_word_median_confidence_index: 0.9200000166893005
      ocr_word_mean_confidence_index: 0.8531481165979685
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
